Added psql client for Postgres 12
If we use Postgres 12, we shoult use psql client version 12 as well.
Otherwise, we may experience errors like:

```
ERROR:  column c.relhasoids does not exist
LINE 1: ...riggers, c.relrowsecurity, c.relforcerowsecurity, c.relhasoi...
```

This is because in Postgres 12, table OIDs are no longer treated as
special columns, and hence the `relhasoid` column is no longer
necessary.

See https://postgresql.verite.pro/blog/2019/04/24/oid-column.html